### ISSUE TITLE
Screen shake stacking

### ISSUE THREAD

**Issue by InspectorSchultz** [HumanoidSandvichDispenser/SupaLidlGame#1]
This might be a feature but the screen shake continually increases in magnitude with each received hit. The camera shakes a bit wildly like a magnitude 9 earthquake after a while. 

Steps for reproduction:
1. Get hit by two enemies at once. 
2. Enemies cause the screen to shake faster than it can reset. 
3. Screen shake will continue to increase.

**Comment by HumanoidSandvichDispenser** [comment]
Stop wasting my time with your novice questions.

**Comment by InspectorSchultz** [comment]
Sorry, my bad I'm still rather new to this platform. I'll try to submit better issue notices from now on.

**Comment by HumanoidSandvichDispenser** [comment]
no problem!! :DD if u need help with creating issues just ask me i'll be happy to help 😊❤️
